[package]
name = "aus-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aus_analyzer"
crate-type = ["cdylib"]

[dependencies]
aus = "0.1.6"
numpy = "0.23.0"
pyo3 = "0.23.1"
